# Generated by Django 3.2.15 on 2022-12-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='murojaat',
            old_name='text',
            new_name='textt',
        ),
    ]
