# Generated by Django 3.2.15 on 2022-12-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_rename_text_murojaat_textt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmailii', models.CharField(max_length=80)),
                ('data', models.DateField()),
            ],
        ),
    ]
