# Generated by Django 3.2.15 on 2022-12-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmail',
            name='data',
        ),
    ]
