# Generated by Django 3.2.15 on 2022-12-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_remove_gmail_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portgmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmaili', models.CharField(max_length=80)),
            ],
        ),
    ]
